#pragma once
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/battle_target_within.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/detect_player_around.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/detect_under_attack.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/move_to_battle_target.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/return_to_prev_behavior_tree.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/spawn_monster.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/start_move_to_random_position.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/suspend_for_seconds.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/suspend_until_player_in_view.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/suspend_until_spawn_monster_dead.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/time_elapsed_after_movement.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/transition_behavior_tree.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/update_battle_target.h"
#include "zerosugar/xr/server/game/instance/ai/behavior_tree/task/use_random_skill.h"

